Repository Leo-Corporation/InternetTest, pull requests merged in 2022-01, with the labels that each got.

#285 Update license copyright year(s)
  LICENSE
Labels: documentation

#287 Add Simplified Chinese translation
  InternetTest/InternetTest/Properties/Resources.zh-CN.resx
Labels: vNext, translation

#290 Version 5.9.1.2201
  InternetTest.Setup/Setup.iss
  InternetTest/InternetTest/App.xaml
  InternetTest/InternetTest/Classes/Global.cs
  InternetTest/InternetTest/InternetTest.csproj
  InternetTest/InternetTest/Pages/SettingsPage.xaml
  InternetTest/InternetTest/Pages/SettingsPage.xaml.cs
Labels: enhancement, vNext, roadmap
