Repository Leo-Corporation/InternetTest, pull requests merged in 2022-05, with the labels that each got.

#317 Updated README
  README.md
Labels: documentation, misc

#315 Updated Simplified Chinese translation
  InternetTest/InternetTest/Properties/Resources.zh-CN.resx
Labels: vNext, translation, roadmap

#325 Version 6.2.0.2205
  InternetTest.Setup/Setup.iss
  InternetTest/InternetTest/App.xaml.cs
  InternetTest/InternetTest/Classes/Global.cs
  InternetTest/InternetTest/Classes/Settings.cs
  InternetTest/InternetTest/InternetTest.csproj
  InternetTest/InternetTest/Pages/DownDetectorPage.xaml.cs
  InternetTest/InternetTest/Pages/LocalizeIPPage.xaml
  InternetTest/InternetTest/Pages/LocalizeIPPage.xaml.cs
  InternetTest/InternetTest/Pages/SettingsPage.xaml
  InternetTest/InternetTest/Pages/SettingsPage.xaml.cs
  InternetTest/InternetTest/Properties/Resources.Designer.cs
  InternetTest/InternetTest/Properties/Resources.en-US.resx
  InternetTest/InternetTest/Properties/Resources.fr-FR.resx
  InternetTest/InternetTest/Properties/Resources.resx
  InternetTest/InternetTest/Properties/Resources.zh-CN.resx
  InternetTest/InternetTest/UserControls/IpHistoryItem.xaml
  InternetTest/InternetTest/UserControls/IpHistoryItem.xaml.cs
Labels: enhancement, vNext, roadmap

#327 Update Chinese translation
  InternetTest/InternetTest/Properties/Resources.zh-CN.resx
Labels: vNext, translation, roadmap

#328 Version 6.2.1.2205
  InternetTest.Setup/Setup.iss
  InternetTest/InternetTest/Classes/Global.cs
  InternetTest/InternetTest/InternetTest.csproj
  InternetTest/InternetTest/Properties/Resources.zh-CN.resx
Labels: vNext, translation, roadmap
