Repository Leo-Corporation/InternetTest, pull requests merged in 2022-08, with the labels that each got.

#344 Added Roadmap
  .github/images/banner.png
  ROADMAP.md
Labels: documentation, roadmap

#363 Update Chinese translation
  InternetTest/InternetTest/Properties/Resources.zh-CN.resx
Labels: enhancement, vNext, translation

#364 Version 7.0.1.2208
  InternetTest.Setup/Setup.iss
  InternetTest/InternetTest/Classes/Global.cs
  InternetTest/InternetTest/InternetTest.csproj
  InternetTest/InternetTest/Pages/SettingsPage.xaml
  InternetTest/InternetTest/Properties/Resources.zh-CN.resx
Labels: vNext, translation
