Repository Leo-Corporation/InternetTest, pull requests merged in 2023-04, with the labels that each got.

#425 Version 7.5.1.2304
  InternetTest/InternetTest/Classes/Global.cs
  InternetTest/InternetTest/InternetTest.csproj
  InternetTest/InternetTest/Properties/Resources.it-IT.resx
Labels: vNext, translation

#427 Update Italian language
  InternetTest/InternetTest/Properties/Resources.it-IT.resx
Labels: vNext, translation

#429 Version 7.5.2.2304
  InternetTest/InternetTest/Classes/Global.cs
  InternetTest/InternetTest/InternetTest.csproj
  InternetTest/InternetTest/Pages/FirstRun/WelcomePage.xaml
  InternetTest/InternetTest/Properties/Resources.Designer.cs
  InternetTest/InternetTest/Properties/Resources.en-US.resx
  InternetTest/InternetTest/Properties/Resources.fr-FR.resx
  InternetTest/InternetTest/Properties/Resources.it-IT.resx
  InternetTest/InternetTest/Properties/Resources.resx
Labels: enhancement, vNext, translation

#432 Update Italian language
  InternetTest/InternetTest/Properties/Resources.it-IT.resx
Labels: translation

#433 Version 7.5.3.2304
  InternetTest/InternetTest/Classes/Global.cs
  InternetTest/InternetTest/InternetTest.csproj
  InternetTest/InternetTest/Pages/SettingsPage.xaml
  InternetTest/InternetTest/Properties/Resources.Designer.cs
  InternetTest/InternetTest/Properties/Resources.en-US.resx
  InternetTest/InternetTest/Properties/Resources.fr-FR.resx
  InternetTest/InternetTest/Properties/Resources.it-IT.resx
  InternetTest/InternetTest/Properties/Resources.resx
  InternetTest/InternetTest/Properties/Resources.zh-CN.resx
Labels: bug, enhancement, vNext, translation
