Repository Leo-Corporation/InternetTest, pull requests merged in 2023-10, with the labels that each got.

#502 Version 7.9.0.2310
  InternetTest/InternetTest/App.xaml
  InternetTest/InternetTest/Classes/AdapterInfo.cs
  InternetTest/InternetTest/Classes/Global.cs
  InternetTest/InternetTest/Classes/Settings.cs
  InternetTest/InternetTest/InternetTest.csproj
  InternetTest/InternetTest/Pages/DnsPage.xaml
  InternetTest/InternetTest/Pages/DnsPage.xaml.cs
  InternetTest/InternetTest/Pages/LocateIpPage.xaml.cs
  InternetTest/InternetTest/Pages/MyIpPage.xaml.cs
  InternetTest/InternetTest/Pages/SettingsPage.xaml
  InternetTest/InternetTest/Pages/SettingsPage.xaml.cs
  InternetTest/InternetTest/Pages/WiFiNetworksPage.xaml
  InternetTest/InternetTest/Pages/WiFiNetworksPage.xaml.cs
  InternetTest/InternetTest/Properties/Resources.Designer.cs
  InternetTest/InternetTest/Properties/Resources.en-US.resx
  InternetTest/InternetTest/Properties/Resources.fr-FR.resx
  InternetTest/InternetTest/Properties/Resources.it-IT.resx
  InternetTest/InternetTest/Properties/Resources.resx
  InternetTest/InternetTest/Properties/Resources.zh-CN.resx
  InternetTest/InternetTest/UserControls/DnsRecordItem.xaml.cs
  InternetTest/InternetTest/UserControls/WiFiNetworkItem.xaml.cs
  InternetTest/InternetTest/Windows/AdapterWindow.xaml
  InternetTest/InternetTest/Windows/AdapterWindow.xaml.cs
Labels: enhancement, vNext

#504 Update Italian language
  InternetTest/InternetTest/Properties/Resources.it-IT.resx
Labels: translation

#505 Version 7.9.1.2310
  InternetTest/InternetTest/Classes/Global.cs
  InternetTest/InternetTest/InternetTest.csproj
  InternetTest/InternetTest/Properties/Resources.it-IT.resx
Labels: enhancement, translation
