Repository Leo-Corporation/InternetTest, pull requests merged in 2023-08, with the labels that each got.

#470 Update Simplified Chinese translation
  InternetTest/InternetTest/Properties/Resources.zh-CN.resx
Labels: vNext, translation

#471 Version 7.7.1.2308
  InternetTest/InternetTest/Classes/Global.cs
  InternetTest/InternetTest/InternetTest.csproj
  InternetTest/InternetTest/Properties/Resources.zh-CN.resx
Labels: enhancement, vNext, translation

#473 Version 7.7.2.2308
  InternetTest/InternetTest/App.xaml.cs
  InternetTest/InternetTest/Classes/Global.cs
  InternetTest/InternetTest/Classes/SynethiaConfig.cs
  InternetTest/InternetTest/InternetTest.csproj
Labels: bug, vNext

#476 Version 7.7.3.2308
  InternetTest/InternetTest/Classes/Global.cs
  InternetTest/InternetTest/InternetTest.csproj
  InternetTest/InternetTest/Pages/WiFiNetworksPage.xaml.cs
Labels: vNext
