Repository Leo-Corporation/InternetTest, pull requests merged in 2023-07, with the labels that each got.

#451 Update italian language
  InternetTest/InternetTest/Properties/Resources.it-IT.resx
Labels: translation

#452 Version 7.6.1.2307
  InternetTest/InternetTest/Classes/Global.cs
  InternetTest/InternetTest/InternetTest.csproj
  InternetTest/InternetTest/Properties/Resources.it-IT.resx
Labels: vNext, translation

#457 Version 7.6.2.2307
  InternetTest.Setup/Setup.iss
  InternetTest/InternetTest/Classes/Global.cs
  InternetTest/InternetTest/Classes/Settings.cs
  InternetTest/InternetTest/InternetTest.csproj
  InternetTest/InternetTest/MainWindow.xaml
  InternetTest/InternetTest/MainWindow.xaml.cs
Labels: bug, enhancement, vNext
