Repository Leo-Corporation/InternetTest, pull requests merged in 2024-08, with the labels that each got.

#600 Version 8.5.0.2408
  .github/images/banner.png
  InternetTest/InternetTest/Classes/Global.cs
  InternetTest/InternetTest/InternetTest.csproj
  InternetTest/InternetTest/Pages/DownDetectorPage.xaml
  InternetTest/InternetTest/Pages/DownDetectorPage.xaml.cs
  InternetTest/InternetTest/Pages/LocateIpPage.xaml
  InternetTest/InternetTest/Pages/LocateIpPage.xaml.cs
  InternetTest/InternetTest/Pages/WiFiPasswordsPage.xaml
  InternetTest/InternetTest/Pages/WiFiPasswordsPage.xaml.cs
  InternetTest/InternetTest/Properties/Resources.Designer.cs
  InternetTest/InternetTest/Properties/Resources.en-US.resx
  InternetTest/InternetTest/Properties/Resources.fr-FR.resx
  InternetTest/InternetTest/Properties/Resources.it-IT.resx
  InternetTest/InternetTest/Properties/Resources.resx
  InternetTest/InternetTest/Properties/Resources.zh-CN.resx
  InternetTest/InternetTest/Themes/Dark.xaml
  InternetTest/InternetTest/Themes/Light.xaml
  InternetTest/InternetTest/UserControls/AdapterItem.xaml.cs
  InternetTest/InternetTest/UserControls/WiFiInfoItem.xaml.cs
  InternetTest/InternetTest/Windows/AdapterWindow.xaml
  InternetTest/InternetTest/Windows/AdapterWindow.xaml.cs
  README.md
Labels: enhancement, vNext

#602 Update Italian language
  InternetTest/InternetTest/Properties/Resources.it-IT.resx
Labels: translation

#603 Version 8.5.1.2408
  InternetTest/InternetTest/Classes/Global.cs
  InternetTest/InternetTest/InternetTest.csproj
  InternetTest/InternetTest/Properties/Resources.it-IT.resx
Labels: vNext, translation

#607 Version 8.5.2.2408
  InternetTest/InternetTest/Classes/Global.cs
  InternetTest/InternetTest/InternetTest.csproj
  InternetTest/InternetTest/Pages/HomePage.xaml.cs
  InternetTest/InternetTest/Pages/SettingsPage.xaml.cs
  InternetTest/InternetTest/Properties/Resources.Designer.cs
  InternetTest/InternetTest/Properties/Resources.en-US.resx
  InternetTest/InternetTest/Properties/Resources.fr-FR.resx
  InternetTest/InternetTest/Properties/Resources.it-IT.resx
  InternetTest/InternetTest/Properties/Resources.resx
  InternetTest/InternetTest/Properties/Resources.zh-CN.resx
Labels: bug, enhancement
