Repository Leo-Corporation/InternetTest, pull requests merged in 2025-03, with the labels that each got.

#646 Version 8.8.0.2503
  .github/workflows/nightly.yml
  InternetTest/InternetTest/App.xaml
  InternetTest/InternetTest/Classes/Global.cs
  InternetTest/InternetTest/InternetTest.csproj
  InternetTest/InternetTest/Pages/DnsPage.xaml
  InternetTest/InternetTest/Pages/DnsPage.xaml.cs
  InternetTest/InternetTest/Pages/RequestsPage.xaml
  InternetTest/InternetTest/Pages/RequestsPage.xaml.cs
  InternetTest/InternetTest/Pages/SettingsPage.xaml
  InternetTest/InternetTest/Pages/SettingsPage.xaml.cs
  InternetTest/InternetTest/Pages/TraceroutePage.xaml.cs
  InternetTest/InternetTest/Properties/Resources.Designer.cs
  InternetTest/InternetTest/Properties/Resources.en-US.resx
  InternetTest/InternetTest/Properties/Resources.fr-FR.resx
  InternetTest/InternetTest/Properties/Resources.it-IT.resx
  InternetTest/InternetTest/Properties/Resources.resx
  InternetTest/InternetTest/Properties/Resources.zh-CN.resx
  InternetTest/InternetTest/Themes/Dark.xaml
  InternetTest/InternetTest/Themes/Light.xaml
  InternetTest/InternetTest/UserControls/ParameterItem.xaml
  InternetTest/InternetTest/UserControls/ParameterItem.xaml.cs
Labels: enhancement, vNext

#648 Italian language update
  InternetTest/InternetTest/Properties/Resources.it-IT.resx
Labels: translation

#649 Version 8.8.1.2503
  InternetTest/InternetTest/Classes/Global.cs
  InternetTest/InternetTest/InternetTest.csproj
  InternetTest/InternetTest/Properties/Resources.it-IT.resx
Labels: vNext, translation

#652 Version 8.8.2.2503
  InternetTest/InternetTest/App.xaml
  InternetTest/InternetTest/Classes/AdapterInfo.cs
  InternetTest/InternetTest/Classes/Global.cs
  InternetTest/InternetTest/InternetTest.csproj
  InternetTest/InternetTest/Pages/IpConfigPage.xaml.cs
  InternetTest/InternetTest/Pages/RequestsPage.xaml.cs
  InternetTest/InternetTest/Pages/WiFiNetworksPage.xaml.cs
  InternetTest/InternetTest/Windows/AdapterWindow.xaml.cs
Labels: enhancement, vNext
